/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddVirtualFolderDto : Add virtual folder dto.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddVirtualFolderDto {
    #[serde(rename = "LibraryOptions", skip_serializing_if = "Option::is_none")]
    pub library_options: Option<Box<models::LibraryOptions>>,
}

impl AddVirtualFolderDto {
    /// Add virtual folder dto.
    pub fn new() -> AddVirtualFolderDto {
        AddVirtualFolderDto {
            library_options: None,
        }
    }
}
