/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceOptions : An entity representing custom options for a device.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceOptions {
    /// Gets the id.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Gets the device id.
    #[serde(rename = "DeviceId", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    /// Gets or sets the custom name.
    #[serde(
        rename = "CustomName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_name: Option<Option<String>>,
}

impl DeviceOptions {
    /// An entity representing custom options for a device.
    pub fn new() -> DeviceOptions {
        DeviceOptions {
            id: None,
            device_id: None,
            custom_name: None,
        }
    }
}
