/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HeaderMatchType {
    #[serde(rename = "Equals")]
    Equals,
    #[serde(rename = "Regex")]
    Regex,
    #[serde(rename = "Substring")]
    Substring,
}

impl std::fmt::Display for HeaderMatchType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Equals => write!(f, "Equals"),
            Self::Regex => write!(f, "Regex"),
            Self::Substring => write!(f, "Substring"),
        }
    }
}

impl Default for HeaderMatchType {
    fn default() -> HeaderMatchType {
        Self::Equals
    }
}
