/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationsSummaryDto : The notification summary DTO.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsSummaryDto {
    /// Gets or sets the number of unread notifications.
    #[serde(rename = "UnreadCount", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
    #[serde(
        rename = "MaxUnreadNotificationLevel",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_unread_notification_level: Option<models::NotificationLevel>,
}

impl NotificationsSummaryDto {
    /// The notification summary DTO.
    pub fn new() -> NotificationsSummaryDto {
        NotificationsSummaryDto {
            unread_count: None,
            max_unread_notification_level: None,
        }
    }
}
